/*global systemDictionary:true */
'use strict';

const allLanguages = (en, de) => ({
    en,
    de,
    ru: en,
    pt: en,
    nl: en,
    fr: en,
    it: en,
    es: en,
    pl: en,
    uk: en,
    'zh-cn': en
});

systemDictionary = {
    "DuoFern Stick settings": allLanguages("DuoFern Stick settings", "DuoFern Stick Einstellungen"),
    "Configure the local Rademacher DuoFern USB stick. Standard baud rate is 115200.": allLanguages("Configure the local Rademacher DuoFern USB stick. Standard baud rate is 115200.", "Konfiguration des lokalen Rademacher DuoFern USB-Sticks. Standard-Baudrate ist 115200."),
    "Serial port": allLanguages("Serial port", "Serieller Port"),
    "Baud rate": allLanguages("Baud rate", "Baudrate"),
    "Dongle serial": allLanguages("Dongle serial", "Dongle-Seriennummer"),
    "Must usually start with 6F.": allLanguages("Must usually start with 6F.", "Muss normalerweise mit 6F beginnen."),
    "Automatically create devices": allLanguages("Automatically create devices", "Ger\u00e4te automatisch anlegen"),
    "Request status on adapter start": allLanguages("Request status on adapter start", "Status beim Adapterstart abfragen"),
    "Preserve values when telegrams are incomplete": allLanguages("Preserve values when telegrams are incomplete", "Werte bei unvollst\u00e4ndigen Telegrammen beibehalten"),
    "Create only supported/observed states per device": allLanguages("Create only supported/observed states per device", "Nur unterst\u00fctzte/erkannte States je Ger\u00e4t anlegen"),
    "Log raw telegrams": allLanguages("Log raw telegrams", "Rohtelegramme protokollieren"),
    "serialPort": allLanguages("Serial port", "Serieller Port"),
    "serialPortHelp": allLanguages("Serial port path, e.g. /dev/serial/by-id/... or /dev/ttyUSB0 or COM5.", "Serieller Port, z. B. /dev/serial/by-id/... oder /dev/ttyUSB0 oder COM5."),
    "baudRate": allLanguages("Baud rate", "Baudrate"),
    "baudRateHelp": allLanguages("DuoFern USB stick normally uses 115200 baud.", "Der DuoFern USB-Stick nutzt normalerweise 115200 Baud."),
    "dongleSerial": allLanguages("DuoFern radio code / DongleSerial", "DuoFern-Funkcode / DongleSerial"),
    "dongleSerialHelp": allLanguages("Six digit DuoFern stick radio code starting with 6F, e.g. 6F1A6F.", "Sechsstelliger DuoFern-Funkcode des Sticks beginnend mit 6F, z. B. 6F1A6F."),
    "deviceCodes": allLanguages("Known device codes", "Bekannte Ger\u00e4tecodes"),
    "deviceCodesHelp": allLanguages("Optional comma/space separated DuoFern device codes.", "Optional kommagetrennte oder leerzeichengetrennte DuoFern-Ger\u00e4tecodes."),
    "autoCreate": allLanguages("Automatically create devices", "Ger\u00e4te automatisch anlegen"),
    "autoCreateHelp": allLanguages("Create devices automatically when telegrams are received.", "Ger\u00e4te automatisch anlegen, wenn Telegramme empfangen werden."),
    "initOnStart": allLanguages("Initialize stick on start", "Stick beim Start initialisieren"),
    "initOnStartHelp": allLanguages("Run DuoFern initialization sequence after opening the serial port.", "DuoFern-Initialisierung nach dem \u00d6ffnen des seriellen Ports ausf\u00fchren."),
    "statusOnStart": allLanguages("Request status on start", "Status beim Start abfragen"),
    "statusOnStartHelp": allLanguages("Request status after startup initialization.", "Nach der Startinitialisierung Status abfragen."),
    "statusAfterCommand": allLanguages("Request status after command", "Status nach Befehl abfragen"),
    "statusAfterCommandHelp": allLanguages("Request device status after control commands.", "Nach Steuerbefehlen den Ger\u00e4testatus abfragen."),
    "periodicStatusPoll": allLanguages("Periodic status polling", "Zyklische Statusabfrage"),
    "periodicStatusPollHelp": allLanguages("Periodically request status for known devices.", "Status bekannter Ger\u00e4te zyklisch abfragen."),
    "periodicStatusPollMs": allLanguages("Polling interval in ms", "Abfrageintervall in ms"),
    "periodicStatusPollMsHelp": allLanguages("Interval for periodic status polling.", "Intervall f\u00fcr zyklische Statusabfragen."),
    "externalActivityPollAll": allLanguages("Poll after external activity", "Nach externer Bedienung abfragen"),
    "externalActivityPollAllHelp": allLanguages("Request status after external remote/control telegrams.", "Status nach externer Bedienung/Fernbedienung abfragen."),
    "ackIncoming": allLanguages("Acknowledge incoming telegrams", "Eingehende Telegramme best\u00e4tigen"),
    "ackIncomingHelp": allLanguages("Send ACK for incoming DuoFern telegrams.", "ACK f\u00fcr eingehende DuoFern-Telegramme senden."),
    "debugRaw": allLanguages("Log raw telegrams", "Rohtelegramme protokollieren"),
    "debugRawHelp": allLanguages("Write raw RX/TX telegrams to the log.", "Rohdaten f\u00fcr RX/TX ins Log schreiben."),
    "flushPartialMs": allLanguages("Partial buffer flush in ms", "Teilpuffer verwerfen nach ms"),
    "flushPartialMsHelp": allLanguages("Timeout for incomplete serial telegram buffers.", "Zeitlimit f\u00fcr unvollst\u00e4ndige serielle Telegrammpuffer."),
    "readAnswerTimeoutMs": allLanguages("Read answer timeout in ms", "Antwort-Timeout in ms"),
    "readAnswerTimeoutMsHelp": allLanguages("Timeout while waiting for stick answers during initialization.", "Timeout beim Warten auf Stick-Antworten w\u00e4hrend der Initialisierung."),
    "commandTimeoutMs": allLanguages("Command timeout in ms", "Befehlstimeout in ms"),
    "commandTimeoutMsHelp": allLanguages("Timeout for queued commands.", "Timeout f\u00fcr Befehle in der Sendequeue."),
    "reconnectIntervalMs": allLanguages("Reconnect interval in ms", "Reconnect-Intervall in ms"),
    "reconnectIntervalMsHelp": allLanguages("Delay before reopening the serial port after disconnect.", "Wartezeit vor erneutem \u00d6ffnen des seriellen Ports nach Verbindungsabbruch.")
};
